version: '3.9'

services:
  web:
    container_name: my-awesome-app-ajg-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

  test:
    container_name: my-awesome-app-ajg-test
    depends_on:
      - "web"
    image: my-awesome-app-ajg_web
    volumes:
    - .:/app
    - ./node_modules:/app/node_modules
    command: ["npm", "test"]